version: "2"

services:
  api:
    container_name: nchan_rest_api
    build: .
    command: bash -c "npm i && npm start"
    volumes:
      - .:/api
      - /app/node_modules
    ports:
      - "7000:3000"
    links:
      - nchan
      - redis
  nchan:
    image: iamaroot/nchan
    volumes:
      - ./nginx:/nginx/conf
    ports:
      - "7001:80"
  redis:
    image: redis:latest
  mongo:
    image: mongo:latest
